public enum TipoToken {
    INT, MAIN, VOID, BREAK, DO, ELSE, IF, WHILE, RETURN, READ, WRITE,

    AUTO, DOUBLE, STRUCT, LONG, SWITCH, CASE, ENUM, REGISTER, TYPEDEF,
    CHAR, EXTERN, UNION, CONST, FLOAT, SHORT, UNSIGNED, CONTINUE, FOR,
    SIGNED, GOTO, SIZEOF, VOLATILE, STATIC, DEFAULT,

    LLAVE_IZQ, LLAVE_DER, CORCHETE_IZQ, CORCHETE_DER, PAREN_IZQ, PAREN_DER, PUNTO_Y_COMA,
    MAS, MENOS, MULTIPLICACION, DIVISION,
    AND_BIT, OR_BIT, NOT_LOGICO, XOR_BIT, NOT_BIT,
    ASIGNACION, MENOR, MAYOR, DESPLAZAR_IZQ, DESPLAZAR_DER,
    IGUALDAD, DIFERENTE, MENOR_IGUAL, MAYOR_IGUAL, AND_LOGICO, OR_LOGICO,
    COMA, PUNTO, FLECHA,

    NUMERO_ENTERO, IDENTIFICADOR, LITERAL_CADENA, LITERAL_CARACTER,

    FIN_ARCHIVO, ERROR
}
