public enum TokenType {
    INT, MAIN, VOID, BREAK, DO, ELSE, IF, WHILE, RETURN, READ, WRITE,

    AUTO, DOUBLE, STRUCT, LONG, SWITCH, CASE, ENUM, REGISTER, TYPEDEF,
    CHAR, EXTERN, UNION, CONST, FLOAT, SHORT, UNSIGNED, CONTINUE, FOR,
    SIGNED, GOTO, SIZEOF, VOLATILE, STATIC, DEFAULT,

    LBRACE, RBRACE, LSQUARE, RSQUARE, LPAR, RPAR, SEMI,
    PLUS, MINUS, MUL_OP, DIV_OP,
    AND_OP, OR_OP, NOT_OP, XOR_OP, NOT_BIT,
    ASSIGN, LT, GT, SHL_OP, SHR_OP,
    EQ, NOTEQ, LTEQ, GTEQ, ANDAND, OROR,
    COMMA, DOT, ARROW,

    INT_NUM, ID, STRING_LIT, CHAR_LIT,

    EOF, ERROR
}
